### ISSUE TITLE
incompatible with intellij 2020.1

### ISSUE THREAD

**Issue by caitsithx** [samvtran/jetbrains-macos-keybindings-for-all#2]
Hey,

Could you please to look at it?

Thank you!
catsithx

**Comment by samvtran** [comment]
Hello again! Thanks so much for reminding me to try the RC for 2020.1. Everything looks compatible, just had to explicitly set the build range to support more than just 2019.

**Comment by caitsithx** [comment]
That is great. Thanks for following up. Are you going to release a new version?

**Comment by samvtran** [comment]
Looks like JetBrains approved the update a few hours ago, so hopefully you should see 1.0.2 pop up as an update in your Plugins settings. If not, I've been uploading the zips to the [release page](https://github.com/samvtran/jetbrains-macos-keybindings-for-all/releases/tag/v1.0.2) for every release for manual installation just in case 😄

**Comment by caitsithx** [comment]
I have it now. thank you for the updating! 

I am really using it! Quite a nice keymap for cross platform users!
