### ISSUE TITLE
Incompatible with version 2020.3 (203)

### ISSUE THREAD

**Issue by yulrizka** [samvtran/jetbrains-macos-keybindings-for-all#3]
Hi, thanks for creating the plugin. 
I wanted to let you know that I just upgraded to 2020.3 EAP and it reported that the plugin is incompatible. (it could be due to only range of supported version) like previous one.

**Comment by samvtran** [comment]
Hi! Thanks for letting me know about the 2020.3 EAP. I was working on a compatible version a couple of days ago but must've missed the published EAP artifacts by a few hours 😓

Good news is that I uploaded a new version to the JetBrains plugin repository, so hopefully they approve the update by the time you're online again. If not, you can grab the plugin sources from the [release page](https://github.com/samvtran/jetbrains-macos-keybindings-for-all/releases/tag/v2.0.0) too. Thanks again!

**Comment by samvtran** [comment]
Release approved by JetBrains last night.
