### ISSUE TITLE
Back Forward change CTRL+ALT+LEFT/RIGHT

### ISSUE THREAD

**Issue by felix9ia** [samvtran/jetbrains-macos-keybindings-for-all#8]
The "Back" and "Forward" shortcuts are most frequently used, and I hope to change them to CTRL+ALT+LEFT/RIGHT.The CTRL + [ / ] keys are not easy to locate and operate blindly.

**Comment by samvtran** [comment]
Hello! Thanks for reaching out about this. Right now <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>→</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>←</kbd> are bound to `NextSplitter` and `PrevSplitter` in this keymap, but I'll confess I never actually use them.

I'll need to think about what makes sense for `NextSplitter` and `PrevSplitter` – whether that's remapping them to something else to free up the shortcuts or removing the shortcuts altogether. Next/PrevSplitter aren't bound in the IntelliJ Windows keymap anyway and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>→</kbd>/<kbd>←</kbd> aren't direct replacements for the macOS keymap's <kbd>Alt</kbd>+<kbd>Tab</kbd>/<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> shortcuts either, so I'm tempted to drop the splitter actions.

I'll think about what makes the most sense and keep you posted!

**Comment by samvtran** [comment]
Thanks again for this request! v3.0.0 has been submitted to the JetBrains Marketplace and should appear as an update hopefully in a day or two 😃

**Comment by felix9ia** [comment]
> Thanks again for this request! v3.0.0 has been submitted to the JetBrains Marketplace and should appear as an update hopefully in a day or two 😃

It should be us thanking you for providing such a great plugin and for coming up with a new solution to this issue so quickly. We are looking forward to version 3.0.
